name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test01
      id: test01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test01
        setup-command: pip install pytest
        command: pytest hello_test.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST01_RESULTS: "${{steps.test01.outputs.result}}"
      with:
        runners: test01
